import type { Metadata } from 'next'

import { geistSans, geistMono } from './fonts'

import { Navbar } from '@/components/navbar'
import { Footer } from '@/components/footer'

import { GeolocationProvider } from '@/shared/hooks/use-geolocation'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-dvh`}
      >
        <GeolocationProvider>
          <Navbar />

          {children}

          <Footer />
        </GeolocationProvider>
      </body>
    </html>
  )
}
