name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --refresh-lockfile --immutable --check-cache

      - name: Linting
        run: yarn lint

      - name: Test
        run: yarn test:coverage
